export interface Task {
  id: string;
  name: string;
  start: Date;
  end: Date;
  category: string;
  group: string;
  color: string;
  label?: string;
  id_next?: string; // Optional: To link tasks
}

const today = new Date();
const year = today.getFullYear();
const month = today.getMonth();

// We will use a fixed day to ensure data for 15th and 16th is always available
const day = 15;

export const tasks: Task[] = [
  // Nhóm mác LC
  {
    id: '1',
    category: 'Nhóm mác LC',
    group: 'Trạm khử KR#1',
    name: 'Task 1',
    start: new Date(year, month, day, 10, 0),
    end: new Date(year, month, day, 16, 0),
    color: 'hsl(203 49% 56% / 0.7)',
    label: 'SWHR82B',
  },
  {
    id: '2',
    category: 'Nhóm mác LC',
    group: 'Trạm khử KR#2',
    name: 'Task 2',
    start: new Date(year, month, day, 6, 0),
    end: new Date(year, month, day, 11, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  // Nhóm mác MC
  {
    id: '3',
    category: 'Nhóm mác MC',
    group: 'Lò thổi BOF#3',
    name: 'Task 3',
    start: new Date(year, month, day, 4, 0),
    end: new Date(year, month, day, 8, 0),
    color: 'hsl(0 0% 70% / 0.7)',
    label: 'Dừng luân phiên',
  },
  {
    id: '12',
    category: 'Nhóm mác MC',
    group: 'Lò thổi BOF#3',
    name: 'Task 12',
    start: new Date(year, month, day, 12, 0),
    end: new Date(year, month, day, 18, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  {
    id: '4',
    category: 'Nhóm mác MC',
    group: 'Lò thổi BOF#4',
    name: 'Task 4',
    start: new Date(year, month, day, 7, 0),
    end: new Date(year, month, day, 13, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
    {
    id: '16',
    category: 'Nhóm mác MC',
    group: 'Lò thổi BOF#4',
    name: 'Task 16',
    start: new Date(year, month, day + 1, 2, 0),
    end: new Date(year, month, day + 1, 9, 0),
    color: 'hsl(203 49% 56% / 0.7)',
    label: 'SWHR82B',
  },
  // Nhóm mác SPAH
  {
    id: '5',
    category: 'Nhóm mác SPAH',
    group: 'Lò thổi BOF#1',
    name: 'Task 5',
    start: new Date(year, month, day, 8, 0),
    end: new Date(year, month, day, 20, 0),
    color: 'hsl(203 49% 56% / 0.7)',
    label: 'SWHR82B',
  },
  {
    id: '13',
    category: 'Nhóm mác SPAH',
    group: 'Lò thổi BOF#1',
    name: 'Task 13',
    start: new Date(year, month, day, 21, 0),
    end: new Date(year, month, day, 22, 0),
    color: 'hsl(0 0% 70% / 0.7)',
    label: 'CT5',
  },
  {
    id: '6',
    category: 'Nhóm mác SPAH',
    group: 'Lò thổi BOF#2',
    name: 'Task 6',
    start: new Date(year, month, day, 2, 0),
    end: new Date(year, month, day, 7, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  {
    id: '14',
    category: 'Nhóm mác SPAH',
    group: 'Lò thổi BOF#2',
    name: 'Task 14',
    start: new Date(year, month, day, 10, 0),
    end: new Date(year, month, day, 20, 0),
    color: 'hsl(60 100% 50% / 0.8)',
    label: 'SAE1008',
  },
  // Nhóm mác phôi vuông
  {
    id: '7',
    category: 'Nhóm mác phôi vuông',
    group: 'Lò thổi BOF#5',
    name: 'Task 7',
    start: new Date(year, month, day, 1, 0),
    end: new Date(year, month, day, 10, 0),
    color: 'hsl(0 100% 50% / 0.8)',
    label: 'DÙNG THAY VLCL',
  },
    {
    id: '17',
    category: 'Nhóm mác phôi vuông',
    group: 'Lò thổi BOF#5',
    name: 'Task 17',
    start: new Date(year, month, day, 11, 0),
    end: new Date(year, month, day, 17, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  // Bảo trì theo kế hoạch
  {
    id: '8',
    category: 'Bảo trì theo kế hoạch',
    group: 'Tinh luyện LF#5',
    name: 'Task 8',
    start: new Date(year, month, day, 8, 0),
    end: new Date(year, month, day, 18, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  {
    id: '9',
    category: 'Bảo trì theo kế hoạch',
    group: 'Tinh luyện LF#3',
    name: 'Task 9',
    start: new Date(year, month, day, 2, 0),
    end: new Date(year, month, day, 12, 0),
    color: 'hsl(60 100% 50% / 0.8)',
    label: 'SAE1008',
  },
  {
    id: 'task-10-link',
    id_next: '10',
    category: 'Bảo trì theo kế hoạch',
    group: 'Tinh luyện LF#2',
    name: 'Task 10',
    start: new Date(year, month, day, 13, 0),
    end: new Date(year, month, day, 22, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  // Sản xuất điều tiết
  {
    id: '10',
    category: 'Sản xuất điều tiết',
    group: 'Tinh luyện LF#1',
    name: 'Task 10',
    start: new Date(year, month, day, 1, 0),
    end: new Date(year, month, day, 15, 0),
    color: 'hsl(203 49% 56% / 0.7)',
    label: 'SWHR82B',
  },
  {
    id: '15',
    category: 'Sản xuất điều tiết',
    group: 'Tinh luyện LF#1',
    name: 'Task 15',
    start: new Date(year, month, day, 16, 0),
    end: new Date(year, month, day, 19, 0),
    color: 'hsl(0 0% 70% / 0.7)',
    label: 'CT5',
  },
  {
    id: '11',
    category: 'Sản xuất điều tiết',
    group: 'Tinh luyện LF#4',
    name: 'Task 11',
    start: new Date(year, month, day, 3, 0),
    end: new Date(year, month, day, 23, 0),
    color: 'hsl(203 49% 56% / 0.7)',
    label: 'SWHR82B',
  },
    {
    id: '18',
    category: 'Sản xuất điều tiết',
    group: 'Tinh luyện LF#4',
    name: 'Task 18',
    start: new Date(year, month, day + 1, 0, 0),
    end: new Date(year, month, day + 1, 8, 0),
    color: 'hsl(60 100% 50% / 0.8)',
    label: 'SAE1008',
  },
  // Dữ liệu mới cho ngày 15, 16
  {
    id: '19',
    category: 'Nhóm mác LC',
    group: 'Trạm khử KR#1',
    name: 'Task 19',
    start: new Date(year, month, 15, 18, 0),
    end: new Date(year, month, 16, 4, 0),
    color: 'hsl(60 100% 50% / 0.8)',
    label: 'SAE1008',
  },
  {
    id: '20',
    category: 'Nhóm mác MC',
    group: 'Lò thổi BOF#4',
    name: 'Task 20',
    start: new Date(year, month, 15, 20, 0),
    end: new Date(year, month, 16, 6, 0),
    color: 'hsl(0 0% 70% / 0.7)',
    label: 'CT3',
  },
  {
    id: '21',
    category: 'Nhóm mác SPAH',
    group: 'Lò thổi BOF#1',
    name: 'Task 21',
    start: new Date(year, month, 16, 5, 0),
    end: new Date(year, month, 16, 15, 0),
    color: 'hsl(145 63% 60% / 0.7)',
    label: 'SAE1006AL',
  },
  {
    id: '22',
    category: 'Bảo trì theo kế hoạch',
    group: 'Tinh luyện LF#2',
    name: 'Task 22',
    start: new Date(year, month, 16, 0, 0),
    end: new Date(year, month, 16, 8, 0),
    color: 'hsl(0 100% 50% / 0.8)',
    label: 'Sửa chữa',
  },
  {
    id: '23',
    category: 'Sản xuất điều tiết',
    group: 'Tinh luyện LF#1',
    name: 'Task 23',
    start: new Date(year, month, 16, 10, 0),
    end: new Date(year, month, 16, 22, 0),
    color: 'hsl(203 49% 56% / 0.7)',
    label: 'SWHR82B',
  },
];
